apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: application-platform.packages.kadras.io.0.0.0
spec:
  licenses:
  - Apache 2.0
  refName: application-platform.packages.kadras.io
  releasedAt: null
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - git: {}
      template:
      - ytt:
          paths:
          - config
      - kbld: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        packages:
          type: object
          additionalProperties: false
          description: Configuration for the platform packages
          properties:
            namespace:
              type: string
              description: The namespace where to install the platform
              default: ""
            exclusions:
              type: array
              description: A list of packages to exclude from being installed
              items:
                type: string
                default: ""
              default: []
        cartographer:
          type: object
          additionalProperties: false
          description: Configuration for Cartographer related packages
          properties:
            blueprints:
              nullable: true
              description: Configuration for the Cartographer Blueprints package
              default: {}
            delivery:
              nullable: true
              description: Configuration for the Cartographer Delivery package
              default: {}
            golden_path_web:
              nullable: true
              description: Configuration for the Cartographer Golden Path Web package
              default: {}
        cert_manager:
          nullable: true
          description: Configuration for the Cert Manager package
          default: {}
        contour:
          nullable: true
          description: Configuration for the Contour package
          default: {}
        conventions:
          type: object
          additionalProperties: false
          description: Configuration for Cartographer Conventions related packages
          properties:
            spring_boot:
              nullable: true
              description: Configuration for the Spring Boot Conventions package
              default: {}
        knative:
          type: object
          additionalProperties: false
          description: Configuration for Knative related packages
          properties:
            serving:
              nullable: true
              description: Configuration for the Knative Serving package
              default: {}
        kpack:
          nullable: true
          description: Configuration for the Kpack package
          default:
            kp_default_repository: ""
        metrics_server:
          nullable: true
          description: Configuration for the Metrics Server package
          default: {}
        namespace_setup:
          nullable: true
          description: Configuration for the Namespace Setup package
          default: {}
        secretgen_controller:
          nullable: true
          description: Configuration for the Secretgen Controller package
          default: {}
        tekton:
          type: object
          additionalProperties: false
          description: Configuration for Tekton related packages
          properties:
            pipelines:
              nullable: true
              description: Configuration for the Tekton Pipelines package
              default: {}
  version: 0.0.0

---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  creationTimestamp: null
  name: application-platform.packages.kadras.io
spec:
  displayName: application-platform
  longDescription: A curated set of Carvel packages to build an application platform or internal developer platform (IDP) on Kubernetes.
  shortDescription: Application platform on Kubernetes.
  categories:
  - internal developer platform
  - application platform
  maintainers:
  - name: Thomas Vitale
  providerName: Arktonix

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    kctrl.carvel.dev/local-fetch-0: .
  creationTimestamp: null
  name: application-platform
spec:
  packageRef:
    refName: application-platform.packages.kadras.io
    versionSelection:
      constraints: 0.0.0
  serviceAccountName: kadras-install-sa
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
